# Server
server.port=8080

# Database - Neon.tech
spring.datasource.url=jdbc:postgresql://ep-orange-tree-aojmu0ex-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vH7XJ2NOUYwm

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.ssl_mode=require

# App
spring.application.name=newsflow-backend